version: 2.1

jobs:
  job-a:
    docker:
      - image: cimg/base:current
    steps:
      - run: echo "job-a ran fine"

  job-b-fails:
    docker:
      - image: cimg/base:current
    steps:
      - run: exit 1

  runs-if-group-not-run:
    docker:
      - image: cimg/base:current
    steps:
      - run: echo "my-group never ran"

job-groups:
  my-group:
    jobs:
      - job-a
      - job-b-fails:
          requires:
            - job-a

workflows:
  main:
    jobs:
      - my-group
      - runs-if-group-not-run:
          requires:
            - my-group: not_run
