version: "2.1"

jobs:
  build:
    machine: true
    steps:
      - checkout

workflows:
  w1:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
