version: 2.1

jobs:
    sleep-job:                                                                                                                                                                                              
      docker:     
        - image: cimg/base:stable
      resource_class: small
      serial-group: my-serial-group
      steps:
        - run:
            name: Sleep for 10 minutes                                                                                                                                                                      
            command: sleep 600
                                                                                                                                                                                                            
workflows:      
    serial-workflow:
      jobs:
        - sleep-job
